kind: Configuration
metadata:
  name: sample-configuration
  namespace: default
spec:
  hcl: |-
    resource "hashicups_order" "edu" {
      items {
        coffee {
          id = 3
        }
        quantity = 2
      }
      items {
        coffee {
          id = 2
        }
        quantity = 2
      }
    }

    output "edu_order" {
      value = hashicups_order.edu
    }
  providerRef:
    name: hashicups
    namespace: default
